export const ACTIONS = {
  ADD_TASK: "ADD_TASK",
  DELETE_TASK: "DELETE_TASK",
  UPDATE_START_TIME: "UPDATE_START_TIME",
  UPDATE_STOP_TIME: "UPDATE_STOP_TIME",

  START_TIME: "START_TIME",
  STOP_TIME: "STOP_TIME",
  UPDATE_TIMER: "UPDATE_TIMER",
};
